version: '3.7'

services:
    songadao-idchain-node:
        build: .
        volumes:
            - './idchain/:/idchain'
        environment:
            - 'EXTRA_OPTS=--gcmode archive --http.api eth,net,web3,txpool'
            - 'SYNCMODE=full'
            # - 'EXTRA_OPTS=--http.api eth,net,web3,txpool'
            # - 'SYNCMODE=light'
        ports:
            - '8545:8545'
            - '8546:8546'
            - '30329:30329'
            - '30329:30329/udp'
