version: '3.7'

services:
    songadao-idchain-archive-node:
        build: .
        volumes:
            - './idchain/:/idchain'
        environment:
            - 'EXTRA_OPTS=--gcmode archive --rpcapi eth,net,web3,txpool'
            - SYNCMODE=full
        ports:
            - '8545:8545'
            - '8546:8546'
            - '30329:30329'
            - '30329:30329/udp'
